### ISSUE TITLE
Ability to accept/reject specific cookie

### ISSUE THREAD

**Issue by misner** [prey/gdpr_rails#1]
Hi,

Awesome engine! thanks for the work.

A question: Following what is recommended by French authorities, we'd like to allow users to pick which service (GA, optimizely, whateva...) they want to accept.
You have an example here of how it would work (https://www.cnil.fr/=> click on the top page banner on "personnaliser" to open the modal).

Is it possible already on gdpr_rails to have
@user.has_consented_cookie? applied to specific cookies ? Let me give you an example, which is basically how the above website cnil.fr handles it:  

A (not logged-in) user sees two lines
- google analytics + 2 buttons accept/reject
- optimizely + 2 buttons accept/reject
- and so on...
And based on the user choice for EACH service, this is stored in the gdpr_rails cookie consent.

Is that how it works today ? is it possible to set up this behavior using gdpr_rails or is it really only "accept all cookies or reject all cookies" for the moment?

Could not figure it out based on the documentation. Thanks

M.

**Comment by michelson** [comment]
Hi , we have not test it yet , but this could be perfectly possible by configuring each cookie as a rule.

example:

### in your initializer
```ruby
  c.add_rule({name: "all_cookie", sessionless: true, on_reject: ->(context){# reject all cookies }), on_accept: ->(context){# accept all cookies })

  c.add_rule({name: "ga_cookie", sessionless: true, on_reject: ->(context){# reject single cookie}), on_accept: ->(context){ accept single cookie}

  c.add_rule({name: "optimizely_cookie", sessionless: true,,on_reject: ->(context){# reject single cookie}), on_accept: ->(context){ accept single cookie}

```
this will give you some methods to work in your model and in your views. so for example you could show all your scripts with `current_user.has_consented_all_cookie?` or handle display for each script separately with `current_user.has_consented_ga_cookie?`

I hope this cover your issue, if not let us know to keep helping you

best

**Comment by misner** [comment]
Sounds great.
Will try it out and let you know
Thanks a lot !
