### ISSUE TITLE
Migrate from Paperclip to ActiveStorage ?

### ISSUE THREAD

**Issue by EtienneDepaulis** [prey/gdpr_rails#12]
This issue is more like an idea as Paperclip deprecation has recently been announced.
A migration to ActiveStorage might be an interesting idea but I don't know if this could be an issue for rails <= 5.1 :/
An interesting article about this migration : https://gorails.com/episodes/migrate-from-paperclip-to-rails-active-storage

**Comment by michelson** [comment]
Since the library supports rails from version 5.1 it would be a good idea.
Said that gemspec should restrict the rails version dependecy range

**Comment by JessicaCGlenn** [comment]
Hey, I've been testing this out at github.com/jessicacglenn/gdpr_rails, It's working well at the moment, but I still need to build out some test and clean it up a little, after which I'll setup a pull request for your perusal.

**Comment by michelson** [comment]
#40

**Comment by michelson** [comment]
activestorage is default on 0.5.0 with an optional paperclip support
