### ISSUE TITLE
peding_policies should be pending_policies

### ISSUE THREAD

**Issue by joshawnard** [prey/gdpr_rails#14]
Typo is breaking code
https://github.com/prey/gdpr_rails/blob/82201b13fe69475dd119bfd63bf58201d056dc9f/app/models/policy_manager/concerns/user_behavior.rb#L90

**Comment by patriciojofre** [comment]
Hello @joshawnard , thanks for your report. This will be fixed in this PR https://github.com/prey/gdpr_rails/pull/15

Pato
