### ISSUE TITLE
Accessing and rendering terms

### ISSUE THREAD

**Issue by almnes** [prey/gdpr_rails#19]
Hi, all info related to terms seems to be on a User object `@user…`. 
Is there a way to easily render out the terms posted and saved in policy_manager_terms?

The reason why I see this as useful and needed is that you can write your policies in the policy manager, and then show it on your privacy page. Say:

`<%= policy_rule_age_content %>`

from there it fetches the last and most updated one that is published and shows that.

**Comment by patriciojofre** [comment]
Hi @almnes, that sounds like a good feature!
currently this is not possible but we could do it or you could send a PR with the implementation :-)

**Comment by patriciojofre** [comment]
@almnes something like this? https://github.com/prey/gdpr_rails/pull/20 🤔

**Comment by almnes** [comment]
@patriciojofre ye #20 pretty intact with what I had in mind.

**Comment by patriciojofre** [comment]
merged https://github.com/prey/gdpr_rails/pull/20
