### ISSUE TITLE
:allow_admins redirects to root_path, which requires admin access

### ISSUE THREAD

**Issue by viamin** [prey/gdpr_rails#23]
If you visit the root path when logged in as a regular user, the :allow_admins callback redirects to root_path, which creates a circular redirect. 

Non-admins should be able to load the app.

Fix is just to add `except: :index` to the callback

**Comment by michelson** [comment]
Hi @viamin , thanks for this contribution

since root_url shows admin information this endpoint should be enabled for admins only. I suggest that this PR instead of bypass protection of index , redirects to pending terms endpoints (`user_terms/pending` )

**Comment by viamin** [comment]
Sounds reasonable. I'll update the PR.
