### ISSUE TITLE
Accept dialog

### ISSUE THREAD

**Issue by Dragsbaek** [prey/gdpr_rails#29]
Does this gem have any accept dialog included? I can see https://preyproject.com/ is using cookiebot. What are people using? Any open source solution?

**Comment by michelson** [comment]
Hi @Dragsbaek , indeed we use cookiebot in our public site. but we use this library in our rails application. This gem provides an interface in which you can see your pending policies along with the portability requests. if you have mounted the engine on `gdpr` then visit `/gdpr/user_terms/pending`
also you could check other routes running `rake routes | grep gdpr` in your command line to see all the gem endpoints.
In our case we had implemented our own accept dialog , this gem also provides json endpoints and ruby dsl to implement it.
