### ISSUE TITLE
Development of invisible option in prey app

### ISSUE THREAD

**Issue by peerzadaaabid** [prey/gdpr_rails#37]
Hello
It is very important that there should be an option which will allow users to hide their application in the phone.

**Comment by michelson** [comment]
Could you describe your use case in more detail? Thanks

**Comment by peerzadaaabid** [comment]
I will submit you a full blog on this feature soon...

**Comment by michelson** [comment]
Thanks @peerzadaaabid , I see. actually this is a repo of a rails plugin for the gdpr regulation. So is not the prey application itself.

But there is a camouflage feature on mobile apps you can check it here. https://help.preyproject.com/article/245-what-is-camouflage-for-android-and-how-does-it-work 

If you want support on the product please refer to the prey community forum https://community.preyproject.com , our team will gladly answer all your questions regarding the product

thanks!
