### ISSUE TITLE
Upgrade to Rails6

### ISSUE THREAD

**Issue by brunto** [prey/gdpr_rails#38]

**Comment by michelson** [comment]
hi @brunto , please can you check out the https://github.com/prey/gdpr_rails/tree/rails-6-active-storage, it has support for rails 6 and active storage, with an optional paperclip support.
the branch is `rails-6-active-storage`

let me know how it works!

**Comment by brunto** [comment]
Hi @michelson we'll check this soon. Thx a lot.

**Comment by michelson** [comment]
released as 0.5.0
