### ISSUE TITLE
Chartkick security vulnerability

### ISSUE THREAD

**Issue by mrsweaters** [prey/gdpr_rails#41]
The chartkick dependency in this repo is fixed to `2.3.4`. Due to a security vulnerability in chartkick, it should be updated to support `>= 3.2.0`.

**Comment by michelson** [comment]
Hi @mrsweaters !, I will release #40 soon , it includes the 3.2.0 dependency of chartkick.
meanwhile you can use this PR. it has rails 6 support active storage, with an optional paperclip support

**Comment by mrsweaters** [comment]
Sounds good! Thank you.
